name: Build a preview version for server
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-preview-server.yml'
      - 'server/**'
      - 'gradle/**'
      - 'gradle.properties'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Build server
        run: ./gradlew :server:buildFatJarCustom

      - name: Upload fat jar
        uses: actions/upload-artifact@v4
        with:
          name: maimaihelper-server-${{ github.sha }}
          path: server/build/libs/
