name: Build a preview version for server
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-preview-client.yml'
      - 'client/**'
      - 'gradle/**'
      - 'gradle.properties'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Build client
        run: ./gradlew :client:assemblePreview

      - name: Upload unsigned apk
        uses: actions/upload-artifact@v4
        with:
          name: maimaihelper-client-${{ github.sha }}
          path: client/build/outputs/apk/preview/
